<% @Language="VBScript" CODEPAGE="65001" %>
<%
Response.CharSet="UTF-8"
Session.CodePage="65001"
Response.CodePage="65001"
%>
<!-- #include file="../common/auth_chk.asp" -->
<!-- #include file="../common/db_conn.asp" -->
<%
    Dim hidden_flag, strSQL
    hidden_flag = request("txt_hidden_flag")

    If (hidden_flag = "btn_search") Then
        Dim v_cbo_mgmt_com, v_cbo_mgmt_class, v_txt_month
        v_cbo_mgmt_com = request("txt_cbo_mgmt_com")
        v_cbo_mgmt_class = request("cbo_mgmt_class")
        v_txt_month = Replace(request("txt_month"), "/", "")

        strSQL = ""
        strSQL = strSQL & " WITH ap_inv_cnt AS ( "
        strSQL = strSQL & " SELECT asset_cd "
        strSQL = strSQL & "      , inv_cnt_dt "
        strSQL = strSQL & "      , mgmt_com_cd "
        strSQL = strSQL & "      , manage_dept_id "
        strSQL = strSQL & "      , purchase_co "
        strSQL = strSQL & "      , manager_emp_id "
        strSQL = strSQL & "      , manager_emp_id_b "
        strSQL = strSQL & "      , specialty "
        strSQL = strSQL & "      , class "
        strSQL = strSQL & "      , ROW_NUMBER() OVER(PARTITION BY asset_cd ORDER BY inv_cnt_dt DESC) as_seq "
        strSQL = strSQL & "   FROM oas_inv_cnt "
        strSQL = strSQL & "  WHERE com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND div_cd        = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND class         = '2' /* 스마트폰 어플 실사 */ "
        strSQL = strSQL & "    AND SUBSTRING(inv_cnt_dt, 1, 6) = '" & v_txt_month & "' "
        strSQL = strSQL & " ) "

        strSQL = strSQL & " , excel_inv_cnt AS ( "
        strSQL = strSQL & " SELECT asset_cd "
        strSQL = strSQL & "      , inv_cnt_dt "
        strSQL = strSQL & "      , mgmt_com_cd "
        strSQL = strSQL & "      , manage_dept_id "
        strSQL = strSQL & "      , purchase_co "
        strSQL = strSQL & "      , manager_emp_id "
        strSQL = strSQL & "      , manager_emp_id_b "
        strSQL = strSQL & "      , specialty "
        strSQL = strSQL & "      , class "
        strSQL = strSQL & "      , ROW_NUMBER() OVER(PARTITION BY asset_cd ORDER BY inv_cnt_dt DESC) as_seq "
        strSQL = strSQL & "   FROM oas_inv_cnt "
        strSQL = strSQL & "  WHERE com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND div_cd        = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND class         = '1' /* 엑셀 실사 */ "
        strSQL = strSQL & "    AND SUBSTRING(inv_cnt_dt, 1, 6) = '" & v_txt_month & "' "
        strSQL = strSQL & " ) "

        strSQL = strSQL & " /* 스마트폰 실사를 우선 적용 */ "
        strSQL = strSQL & " , inv_cnt AS ( "
        strSQL = strSQL & " SELECT asset_cd "
        strSQL = strSQL & "      , inv_cnt_dt "
        strSQL = strSQL & "      , mgmt_com_cd "
        strSQL = strSQL & "      , manage_dept_id "
        strSQL = strSQL & "      , purchase_co "
        strSQL = strSQL & "      , manager_emp_id "
        strSQL = strSQL & "      , manager_emp_id_b "
        strSQL = strSQL & "      , specialty "
        strSQL = strSQL & "      , class "
        strSQL = strSQL & "   FROM ap_inv_cnt "
        strSQL = strSQL & "  WHERE as_seq = 1 "

        strSQL = strSQL & "  UNION ALL "
        strSQL = strSQL & " SELECT asset_cd "
        strSQL = strSQL & "      , inv_cnt_dt "
        strSQL = strSQL & "      , mgmt_com_cd "
        strSQL = strSQL & "      , manage_dept_id "
        strSQL = strSQL & "      , purchase_co "
        strSQL = strSQL & "      , manager_emp_id "
        strSQL = strSQL & "      , manager_emp_id_b "
        strSQL = strSQL & "      , specialty "
        strSQL = strSQL & "      , class "
        strSQL = strSQL & "   FROM excel_inv_cnt "
        strSQL = strSQL & "  WHERE as_seq = 1 "
        strSQL = strSQL & "    AND NOT EXISTS (SELECT * "
        strSQL = strSQL & "                      FROM ap_inv_cnt "
        strSQL = strSQL & "                     WHERE as_seq = 1 "
        strSQL = strSQL & "                       AND excel_inv_cnt.asset_cd = asset_cd) "
        strSQL = strSQL & " ) "

        strSQL = strSQL & " /* 재고조정일 기준 보유 자산 */ "
        strSQL = strSQL & " , asset_vary AS ( "
        strSQL = strSQL & " SELECT com_cd "
        strSQL = strSQL & "      , div_cd "
        strSQL = strSQL & "      , asset_cd "
        strSQL = strSQL & "      , vary_dt "
        strSQL = strSQL & "      , seq "
        strSQL = strSQL & "      , ROW_NUMBER() OVER(PARTITION BY asset_cd ORDER BY vary_dt DESC, seq DESC ) AS vary_seq "
        strSQL = strSQL & "      , vary_div "
        strSQL = strSQL & "      , mgmt_com_cd "
        strSQL = strSQL & "      , manage_dept_id "
        strSQL = strSQL & "      , purchase_co "
        strSQL = strSQL & "      , manager_emp_id "
        strSQL = strSQL & "      , manager_emp_id_b "
        strSQL = strSQL & "      , specialty "
        strSQL = strSQL & "      , create_class "
        strSQL = strSQL & "   FROM oas_asset_vary "
        strSQL = strSQL & "  WHERE create_class <> '99' "
        strSQL = strSQL & "    AND com_cd    = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND div_cd    = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND SUBSTRING(vary_dt, 1, 6) <= '" & v_txt_month & "' "
        strSQL = strSQL & " ) "

        strSQL = strSQL & " , hold_asset AS ( "
        strSQL = strSQL & " SELECT oas.com_cd "
        strSQL = strSQL & "      , oas.div_cd "
        strSQL = strSQL & "      , oas.asset_cd                          /* 자산코드 */ "
        strSQL = strSQL & "      , asv.vary_dt                           /* 최종 변동 일 */ "
        strSQL = strSQL & "      , asv.vary_div                          /* 최종 변동 구분 코드 */ "
        strSQL = strSQL & "      , mvr.cd_desc      AS asset_status      /* 최종 변동에 따른 자산 상태 코드 (보유, 매각, 폐기) */ "
        strSQL = strSQL & "      , asv.mgmt_com_cd                       /* 최종 관리 회사 코드 */ "
        strSQL = strSQL & "      , mcm.cd_nm_loc    AS mgmt_com_nm       /* 최종 관리 회사 명 */ "
        strSQL = strSQL & "      , asv.manage_dept_id                    /* 최종 관리부서 코드 */ "
        strSQL = strSQL & "      , hdm.dept_loc_nm  AS manage_dept_nm    /* 최종 관리부서 명 */ "
        strSQL = strSQL & "      , asv.purchase_co                       /* 최종 구매법인 */ "
        strSQL = strSQL & "      , puc.cd_nm_loc    AS purchase_co_nm    /* 최종 구매법인 명 */ "
        strSQL = strSQL & "      , asv.manager_emp_id                    /* 최종 관리자(정) 코드 */ "
        strSQL = strSQL & "      , hem.emp_loc_nm   AS manager_emp_nm    /* 최종 관리자(정) 명 */ "
        strSQL = strSQL & "      , asv.manager_emp_id_b                  /* 최종 관리자(부) 코드 */ "
        strSQL = strSQL & "      , hem_b.emp_loc_nm AS manager_emp_nm_b  /* 최종 관리자(부) 명 */ "
        strSQL = strSQL & "      , asv.create_class AS create_class      /* 자산변동 생성구분 */ "
        strSQL = strSQL & "   FROM oas_asset oas "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN asset_vary asv "
        strSQL = strSQL & "     ON oas.asset_cd     = asv.asset_cd "
        strSQL = strSQL & "    AND asv.vary_seq     = 1 "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN mco_code mvr "
        strSQL = strSQL & "     ON asv.com_cd       = mvr.com_cd "
        strSQL = strSQL & "    AND asv.vary_div     = mvr.cd_data "
        strSQL = strSQL & "    AND mvr.cd_class     = 'ASDVCL' "
        strSQL = strSQL & "    AND mvr.use_flag     = '1' "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN mco_code mcm "
        strSQL = strSQL & "     ON asv.com_cd       = mcm.com_cd "
        strSQL = strSQL & "    AND asv.mgmt_com_cd  = mcm.cd_data "
        strSQL = strSQL & "    AND mcm.cd_class     = 'ASMGCM' "
        strSQL = strSQL & "    AND mcm.use_flag     = '1' "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN mco_code puc "
        strSQL = strSQL & "     ON asv.com_cd       = puc.com_cd "
        strSQL = strSQL & "    AND asv.purchase_co  = puc.cd_data "
        strSQL = strSQL & "    AND puc.cd_class     = 'ASPUCO' "
        strSQL = strSQL & "    AND puc.use_flag     = '1' "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN hor_department   hdm "
        strSQL = strSQL & "     ON asv.com_cd           = hdm.com_cd "
        strSQL = strSQL & "    AND asv.div_cd           = hdm.div_cd "
        strSQL = strSQL & "    AND asv.manage_dept_id   = hdm.dept_id "
        strSQL = strSQL & "    AND CONVERT(VARCHAR(8), getdate(), 112) between hdm.appnt_dt and hdm.abolish_dt "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN hhm_emp_master   hem "
        strSQL = strSQL & "     ON asv.com_cd           = hem.com_cd "
        strSQL = strSQL & "    AND asv.div_cd           = hem.div_cd "
        strSQL = strSQL & "    AND asv.manager_emp_id   = hem.emp_id "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN hhm_emp_master   hem_b "
        strSQL = strSQL & "     ON asv.com_cd            = hem_b.com_cd "
        strSQL = strSQL & "    AND asv.div_cd            = hem_b.div_cd "
        strSQL = strSQL & "    AND asv.manager_emp_id_b  = hem_b.emp_id "
        strSQL = strSQL & "  WHERE oas.com_cd            = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND oas.div_cd            = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND mvr.cd_desc           = '10'  /* 보유중인 자산만 */ "
        strSQL = strSQL & "    AND oas.create_class <> '99' "
        strSQL = strSQL & " ) "

        strSQL = strSQL & " , qry_std AS ( "
        strSQL = strSQL & " SELECT asset_cd "
        strSQL = strSQL & "   FROM inv_cnt "

        strSQL = strSQL & " UNION "
        strSQL = strSQL & " SELECT asset_cd "
        strSQL = strSQL & "   FROM hold_asset "
        strSQL = strSQL & "  WHERE com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND div_cd        = N'" & session("div_cd") & "' "
        strSQL = strSQL & " ) "

        strSQL = strSQL & " SELECT qst.asset_cd            /* 자산코드 */ "
        strSQL = strSQL & "      , oas.asset_nm            /* 자산명 */ "
        strSQL = strSQL & "      , oas.asset_class         /* 자산구분코드 */ "
        strSQL = strSQL & "      , oas.asset_class_nm      /* 자산구분명 */ "
        strSQL = strSQL & "      , oas.mgmt_class          /* 자산관리구분코드 */ "
        strSQL = strSQL & "      , oas. mgmt_class_nm      /* 자산관리구분명 */ "
        strSQL = strSQL & "      , has.mgmt_com_cd         /* 기존 관리 회사 코드 */ "
        strSQL = strSQL & "      , has.mgmt_com_nm         /* 기존 관리 회사 명 */ "
        strSQL = strSQL & "      , has.manage_dept_id      /* 기존 관리부서 코드 */ "
        strSQL = strSQL & "      , has.manage_dept_nm      /* 기존 관리부서 명 */ "
        strSQL = strSQL & "      , has.purchase_co         /* 기존 구매법인 */ "
        strSQL = strSQL & "      , has.purchase_co_nm      /* 기존 구매볍인명 */ "
        strSQL = strSQL & "      , has.manager_emp_id      /* 기존 관리자(정) 코드 */ "
        strSQL = strSQL & "      , has.manager_emp_nm      /* 기존 관리자(정) 명 */ "
        strSQL = strSQL & "      , has.manager_emp_id_b    /* 기존 관리자(부) 코드 */ "
        strSQL = strSQL & "      , has.manager_emp_nm_b    /* 기존 관리자(부) 명 */ "
        strSQL = strSQL & "      , aas.mgmt_com_cd       AS mgmt_com_cd_at         /* 최종 관리 회사 코드 */ "
        strSQL = strSQL & "      , mcm.cd_nm_loc         AS mgmt_com_nm_at         /* 최종 관리 회사 명 */ "
        strSQL = strSQL & "      , aas.manage_dept_id    AS manage_dept_id_at      /* 최종 관리부서 코드 */ "
        strSQL = strSQL & "      , hdm.dept_loc_nm       AS manage_dept_nm_at      /* 최종 관리부서 명 */ "
        strSQL = strSQL & "      , aas.purchase_co       AS purchase_co_at         /* 실사 관리부서 코드 */ "
        strSQL = strSQL & "      , puc.cd_nm_loc         AS purchase_co_nm_at      /* 실사 관리부서 명 */ "
        strSQL = strSQL & "      , aas.manager_emp_id    AS manager_emp_id_at      /* 최종 관리자(정) 코드 */ "
        strSQL = strSQL & "      , hem.emp_loc_nm        AS manager_emp_nm_at      /* 최종 관리자(정) 명 */ "
        strSQL = strSQL & "      , aas.manager_emp_id_b  AS manager_emp_id_b_at    /* 최종 관리자(부) 코드 */ "
        strSQL = strSQL & "      , hem_b.emp_loc_nm      AS manager_emp_nm_b_at    /* 최종 관리자(부) 명 */ "
        strSQL = strSQL & "      , aas.inv_cnt_dt      /* 실사일 */ "
        strSQL = strSQL & "      , aas.class           /* 실사구분 */ "
        strSQL = strSQL & "      , mic.cd_nm_loc         AS at_class_nm            /* 실사구분 */ "
        strSQL = strSQL & "      , aas.specialty       /* 비고 */ "
        strSQL = strSQL & "      , 0     AS chk_flag "
        strSQL = strSQL & "      , CASE WHEN ISNULL(has.mgmt_com_cd, '') + ISNULL(has.manage_dept_id, '') + ISNULL(has.purchase_co, '') + ISNULL(has.manager_emp_id, '') + ISNULL(has.manager_emp_id_b , '') "
        strSQL = strSQL & "               <> ISNULL(aas.mgmt_com_cd, '') + ISNULL(aas.manage_dept_id, '') + ISNULL(aas.purchase_co, '') + ISNULL(aas.manager_emp_id, '') + ISNULL(aas.manager_emp_id_b , '') "
        strSQL = strSQL & "              THEN 1 "
        strSQL = strSQL & "              ELSE 0 "
        strSQL = strSQL & "         END diff_flag "
        strSQL = strSQL & "      , CASE WHEN ISNULL(has.mgmt_com_cd, '') + ISNULL(has.manage_dept_id, '') + ISNULL(has.purchase_co, '') + ISNULL(has.manager_emp_id, '') + ISNULL(has.manager_emp_id_b , '') "
        strSQL = strSQL & "                = ISNULL(aas.mgmt_com_cd, '') + ISNULL(aas.manage_dept_id, '') + ISNULL(aas.purchase_co, '') + ISNULL(aas.manager_emp_id, '') + ISNULL(aas.manager_emp_id_b , '') "
        strSQL = strSQL & "             THEN '' "
        strSQL = strSQL & "             ELSE CASE WHEN ISNULL(has.mgmt_com_cd, '') <> '' AND ISNULL(aas.mgmt_com_cd, '') = '' "
        strSQL = strSQL & "                       THEN '40'  /* 폐기 */ "
        strSQL = strSQL & "                       ELSE '20'  /* 이외는 모두 이동, 취득은 사용자 선택 */ "
        strSQL = strSQL & "                   END "
        strSQL = strSQL & "         END  AS vary_div  /* 변동구분 (실사 조치) */ "
        strSQL = strSQL & "   FROM qry_std qst "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN v_oas_asset  oas "
        strSQL = strSQL & "     ON oas.com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND oas.div_cd        = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND qst.asset_cd      = oas.asset_cd "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN hold_asset  has  /* 기존자산 */ "
        strSQL = strSQL & "     ON qst.asset_cd      = has.asset_cd "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN inv_cnt  aas    /* 실사자산 */ "
        strSQL = strSQL & "     ON qst.asset_cd      = aas.asset_cd "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN mco_code mcm "
        strSQL = strSQL & "     ON mcm.com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND aas.mgmt_com_cd   = mcm.cd_data "
        strSQL = strSQL & "    AND mcm.cd_class      = 'ASMGCM' "
        strSQL = strSQL & "    AND mcm.use_flag      = '1' "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN mco_code puc "
        strSQL = strSQL & "     ON puc.com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND aas.purchase_co   = puc.cd_data "
        strSQL = strSQL & "    AND puc.cd_class      = 'ASPUCO' "
        strSQL = strSQL & "    AND puc.use_flag      = '1' "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN hor_department   hdm "
        strSQL = strSQL & "     ON hdm.com_cd            = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND hdm.div_cd            = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND aas.manage_dept_id    = hdm.dept_id "
        strSQL = strSQL & "    AND CONVERT(VARCHAR(8), getdate(), 112) between hdm.appnt_dt and hdm.abolish_dt "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN hhm_emp_master   hem "
        strSQL = strSQL & "     ON hem.com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND hem.div_cd        = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND aas.manager_emp_id   = hem.emp_id "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN hhm_emp_master   hem_b "
        strSQL = strSQL & "     ON hem_b.com_cd      = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND hem_b.div_cd      = N'" & session("div_cd") & "' "
        strSQL = strSQL & "    AND aas.manager_emp_id_b  = hem_b.emp_id "
        strSQL = strSQL & "   LEFT "
        strSQL = strSQL & "   JOIN mco_code mic "
        strSQL = strSQL & "     ON mic.com_cd        = N'" & session("com_cd") & "' "
        strSQL = strSQL & "    AND aas.class         = mic.cd_data "
        strSQL = strSQL & "    AND mic.cd_class      = 'ASICCL' "
        strSQL = strSQL & "    AND mic.use_flag      = '1' "
        strSQL = strSQL & "  WHERE 1=1 "

        If (v_cbo_mgmt_com <> "") Then
            strSQL = strSQL & "    AND (has.mgmt_com_cd = N'" & v_cbo_mgmt_com & "' OR aas.mgmt_com_cd = N'" & v_cbo_mgmt_com & "') "
        ElseIf Not (session("system_admin_flag") = "1" Or session("notice_admin_flag") = "1") Then
            strSQL = strSQL & "    AND (has.mgmt_com_cd = N'" & v_cbo_mgmt_com & "' OR aas.mgmt_com_cd = N'" & v_cbo_mgmt_com & "') "
        End If

        If (v_cbo_mgmt_class <> "") Then strSQL = strSQL & "    AND oas.mgmt_class = N'" & v_cbo_mgmt_class & "' "

        strSQL = strSQL & "    AND ISNULL(has.mgmt_com_cd, '') + ISNULL(has.manage_dept_id, '') + ISNULL(has.purchase_co, '') + ISNULL(has.manager_emp_id, '') + ISNULL(has.manager_emp_id_b , '') "
        strSQL = strSQL & "     <> ISNULL(aas.mgmt_com_cd, '') + ISNULL(aas.manage_dept_id, '') + ISNULL(aas.purchase_co, '') + ISNULL(aas.manager_emp_id, '') + ISNULL(aas.manager_emp_id_b , '') "

        strSQL = strSQL & "  ORDER "
        strSQL = strSQL & "     BY oas.asset_nm "
        strSQL = strSQL & "      , oas.asset_cd "

        Response.write "<script> "
        Response.write "    var trCnt = parent.$('#grd01 tr').length; "
        Response.write "    var innerHtml = ''; "
        Response.write "    parent.$('#grd01_body').empty(); "

        objRS.open strSQL, objDBConn
        If Not (objRS.eof Or objRS.bof) Then
            While Not objRS.eof
                Response.write "    innerHtml = ''; "
                Response.write "    innerHtml += '<tr>'; "
                Response.write "    innerHtml += '    <td class=tcenter>" & objRS("asset_cd") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & Replace(objRS("asset_nm"), "'", "\'") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("mgmt_com_nm") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("manage_dept_nm") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("purchase_co_nm") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("manager_emp_nm") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("manager_emp_nm_b") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("mgmt_com_nm_at") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("manage_dept_nm_at") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("purchase_co_nm_at") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("manager_emp_nm_at") & "</td>'; "
                Response.write "    innerHtml += '    <td>" & objRS("manager_emp_nm_b_at") & "</td>'; "
                Response.write "    innerHtml += '</tr>'; "
                Response.write "    parent.$('#grd01 > #grd01_body:last').append(innerHtml); "
                objRS.movenext
            Wend
        End If
        Response.write "</script>"
       objRS.Close: objDBConn.Close

    End If
%>
